# -------------------------------
# Base SDK image (dynamic version)
# -------------------------------
ARG DOTNET_VERSION=9.0
FROM mcr.microsoft.com/dotnet/sdk:${DOTNET_VERSION}

RUN useradd -u 1000 -m vscode
USER 1000:1000

WORKDIR /workspaces/app

CMD ["sleep", "infinity"]
